//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int CurriculumID { get; set; }
        public int GroupID { get; set; }
        public int SubjectID { get; set; }
        public int Hours { get; set; }
        public int Complexity { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
