//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolScheduleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRestrictions
    {
        public int RestrictionID { get; set; }
        public int TeacherID { get; set; }
        public string DayOfWeek { get; set; }
    
        public virtual Teachers Teachers { get; set; }
    }
}
